### ISSUE TITLE
Doesn't work at all - roslyn missing

### ISSUE THREAD

**Issue by tabinnorway** [OfficeDev/msteams-samples-hello-world-csharp#8]
got clone...
open in VS 2017
Press F5
Could not find a part of the path '...\msteams-samples-hello-world-csharp\Microsoft.Teams.Samples.HelloWorld.Web\bin\roslyn\csc.exe'.

**Comment by tabinnorway** [comment]
Update to compiler package 3.0.0

**Comment by mjanulaitis** [comment]
I installed Microsoft.Net.Compilers 3.0.0 but now the application does not compile.
